export const FILES = [
  {
    id: 1,
    name: "Tremebhdh.png",
    type: "file",
    extension: "png",
    size: 76485,
    owner: "Gabriela Garrido",
    location: "My Files",
    createdAt: "12/28/2020",
    path: "/images/general/image4.png",
  },
  {
    id: 2,
    name: "Background.jpg",
    type: "file",
    extension: "jpg",
    size: 48910,
    owner: "John Smith",
    location: "My Files",
    createdAt: "12/28/2020",
    path: "/images/general/image5.png",
  },
  {
    id: 3,
    name: "Slide1.web",
    type: "file",
    extension: "web",
    size: 153240,
    location: "My Files",
    createdAt: "12/28/2020",
    owner: "Mark Stewart",
  },
  {
    id: 4,
    name: "Get_Started_Complete.zip",
    type: "file",
    extension: "zip",
    size: 66710,
    location: "My Files",
    owner: "Kira Maru",
    createdAt: "12/28/2020",
  },
  {
    id: 5,
    name: "Background.jpg",
    type: "file",
    extension: "jpg",
    size: 48910,
    owner: "John Smith",
    location: "My Files",
    createdAt: "12/28/2020",
    path: "/images/general/image7.png",
  },
  {
    id: 6,
    name: "Slide1.web",
    type: "file",
    extension: "web",
    size: 153240,
    owner: "Mark Stewart",
    location: "My Files",
    createdAt: "12/28/2020",
  },
  {
    id: 7,
    name: "Get_Started_Complete.zip",
    type: "file",
    extension: "zip",
    size: 66710,
    owner: "Kira Maru",
    createdAt: "12/28/2020",
    location: "My Files",
  },
  {
    id: 8,
    name: "Background.jpg",
    type: "file",
    extension: "jpg",
    size: 48910,
    owner: "John Smith",
    location: "My Files",
    createdAt: "12/28/2020",
    path: "/images/general/image8.png",
  },
];

export const FOLDERS = [
  {
    id: 1,
    name: "My Files",
    updated_at: "12/12/2023",
  },
  {
    id: 2,
    name: "Projects",
    updated_at: "12/12/2023",
  },
];
